# Generated by Django 6.0.3 on 2026-03-19 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_type', models.CharField(max_length=255)),
                ('root_cause', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('closed', 'Closed')], default='open', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ncrs', to='projects.project')),
            ],
        ),
    ]
