# Generated by Django 6.0.3 on 2026-03-19 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(help_text='Owning customer for RBAC filtering.', on_delete=django.db.models.deletion.PROTECT, related_name='customer_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
