# Generated by Django 6.0.3 on 2026-03-19 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_documents_approvals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Owning customer for RBAC filtering.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
