# Generated by Django 6.0.3 on 2026-03-19 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.PositiveIntegerField(default=0)),
                ('defects', models.PositiveIntegerField(default=0)),
                ('shift', models.CharField(choices=[('day', 'Day'), ('night', 'Night')], default='day', max_length=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='projects.project')),
            ],
        ),
    ]
